import type { Event, EventSchedule, MemoryPost } from "@/types/evespace";

const now = new Date().toISOString();

export const mockEvents: Event[] = [
  {
    id: "icu-festival-2026",
    title: "ICU Festival 2026",
    slug: "icu-festival-2026",
    description:
      "A campus-wide festival of food stalls, club showcases, night performances, and shared student memories.",
    category: "University Festival",
    startTime: "2026-10-26T10:00:00+09:00",
    endTime: "2026-10-26T19:00:00+09:00",
    locationName: "International Christian University",
    address: "3-10-2 Osawa, Mitaka, Tokyo",
    googleMapsUrl: "https://maps.google.com/?q=International+Christian+University",
    latitude: 35.684,
    longitude: 139.529,
    sellingGoods: true,
    goodsDescription:
      "Festival towels, club zines, handmade accessories, and limited sweets are available near the main quad.",
    boardBackgroundTheme: "festival_night",
    moderationMode: "pre_approval",
    visibility: "public",
    starX: 2600,
    starY: 4300,
    starSize: 1.25,
    starBrightness: 1.25,
    createdBy: null,
    createdByProfileId: null,
    createdByClerkUserId: null,
    verificationStatus: "verified",
    verificationRequestedAt: now,
    verificationReviewedAt: now,
    verificationReviewedBy: "demo-platform-admin",
    verificationNotes: "Demo verified event.",
    officialWebsiteUrl: "https://icu.ac.jp",
    officialSocialUrl: null,
    organizerEmail: "festival@example.edu",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "starlight-wedding",
    title: "Mika & Ren Starlight Wedding",
    slug: "mika-ren-starlight-wedding",
    description:
      "A warm evening wedding where guests can leave photos, notes, and small wishes for the couple.",
    category: "Wedding",
    startTime: "2026-06-13T17:00:00+09:00",
    endTime: "2026-06-13T21:00:00+09:00",
    locationName: "Yokohama Harbor Terrace",
    address: "Yokohama, Kanagawa",
    googleMapsUrl: "https://maps.google.com/?q=Yokohama+Harbor+Terrace",
    latitude: 35.4437,
    longitude: 139.638,
    sellingGoods: false,
    goodsDescription: null,
    boardBackgroundTheme: "pastel_sky",
    moderationMode: "pre_approval",
    visibility: "public",
    starX: 6900,
    starY: 2800,
    starSize: 1.4,
    starBrightness: 1.35,
    createdBy: null,
    createdByProfileId: null,
    createdByClerkUserId: null,
    verificationStatus: "pending_review",
    verificationRequestedAt: now,
    verificationReviewedAt: null,
    verificationReviewedBy: null,
    verificationNotes: null,
    officialWebsiteUrl: null,
    officialSocialUrl: null,
    organizerEmail: "hosts@example.com",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "tokyo-creator-night",
    title: "Tokyo Creator Night",
    slug: "tokyo-creator-night",
    description:
      "A showcase and networking night for student designers, musicians, builders, and visual artists.",
    category: "Community",
    startTime: "2026-05-08T18:30:00+09:00",
    endTime: "2026-05-08T22:00:00+09:00",
    locationName: "Shibuya Stream Hall",
    address: "Shibuya, Tokyo",
    googleMapsUrl: "https://maps.google.com/?q=Shibuya+Stream+Hall",
    latitude: 35.658,
    longitude: 139.702,
    sellingGoods: true,
    goodsDescription:
      "Artist prints and small-batch creator goods will be sold beside the entrance lounge.",
    boardBackgroundTheme: "dark_minimal",
    moderationMode: "post_first",
    visibility: "public",
    starX: 4800,
    starY: 6500,
    starSize: 1.15,
    starBrightness: 1.15,
    createdBy: null,
    createdByProfileId: null,
    createdByClerkUserId: null,
    verificationStatus: "unverified",
    verificationRequestedAt: null,
    verificationReviewedAt: null,
    verificationReviewedBy: null,
    verificationNotes: null,
    officialWebsiteUrl: null,
    officialSocialUrl: null,
    organizerEmail: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockSchedules: EventSchedule[] = [
  {
    id: "schedule-1",
    eventId: "icu-festival-2026",
    title: "Opening Ceremony",
    description: "Welcome remarks and opening performance on the main stage.",
    locationName: "Main Stage",
    startTime: "2026-10-26T10:00:00+09:00",
    endTime: "2026-10-26T10:30:00+09:00",
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "schedule-2",
    eventId: "icu-festival-2026",
    title: "Food Stall Tour",
    description: "A guided walk through the club food stalls.",
    locationName: "Main Quad",
    startTime: "2026-10-26T11:30:00+09:00",
    endTime: "2026-10-26T12:30:00+09:00",
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "schedule-3",
    eventId: "icu-festival-2026",
    title: "Dance Performance",
    description: "Student dance groups perform on the outdoor stage.",
    locationName: "Outdoor Stage",
    startTime: "2026-10-26T13:00:00+09:00",
    endTime: "2026-10-26T14:00:00+09:00",
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "schedule-4",
    eventId: "starlight-wedding",
    title: "Reception Opens",
    description: "Guests arrive, take photos, and leave first notes.",
    locationName: "Harbor Hall",
    startTime: "2026-06-13T17:00:00+09:00",
    endTime: "2026-06-13T17:45:00+09:00",
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "schedule-5",
    eventId: "tokyo-creator-night",
    title: "Creator Showcase",
    description: "Lightning demos from student makers and artists.",
    locationName: "Main Room",
    startTime: "2026-05-08T19:00:00+09:00",
    endTime: "2026-05-08T20:15:00+09:00",
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockMemoryPosts: MemoryPost[] = [
  {
    id: "memory-1",
    eventId: "icu-festival-2026",
    userId: null,
    profileId: null,
    clerkUserId: null,
    authorDisplayName: "Aki",
    imageUrl:
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=900&q=80",
    storagePath: null,
    caption: "The night performance made the whole campus feel like a tiny galaxy.",
    frameStyle: "polaroid",
    stickyNoteStyle: "yellow",
    stickerId: null,
    boardX: null,
    boardY: null,
    rotation: -1.5,
    status: "approved",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "memory-2",
    eventId: "icu-festival-2026",
    userId: null,
    profileId: null,
    clerkUserId: null,
    authorDisplayName: "Mina",
    imageUrl:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=80",
    storagePath: null,
    caption: "Food stalls, music, and everyone laughing in the cold air.",
    frameStyle: "space_glow",
    stickyNoteStyle: "glass",
    stickerId: null,
    boardX: null,
    boardY: null,
    rotation: 1,
    status: "approved",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "memory-3",
    eventId: "starlight-wedding",
    userId: null,
    profileId: null,
    clerkUserId: null,
    authorDisplayName: "Sora",
    imageUrl:
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80",
    storagePath: null,
    caption: "A soft evening by the water. Congratulations, Mika and Ren.",
    frameStyle: "soft_rounded",
    stickyNoteStyle: "pink",
    stickerId: null,
    boardX: null,
    boardY: null,
    rotation: 0.5,
    status: "approved",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "memory-4",
    eventId: "tokyo-creator-night",
    userId: null,
    profileId: null,
    clerkUserId: null,
    authorDisplayName: "Nao",
    imageUrl:
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=900&q=80",
    storagePath: null,
    caption: "Left with three new project ideas and a very full camera roll.",
    frameStyle: "film",
    stickyNoteStyle: "blue",
    stickerId: null,
    boardX: null,
    boardY: null,
    rotation: -0.75,
    status: "approved",
    createdAt: now,
    updatedAt: now,
  },
];
