import type { Sticker, StickerCategory, StickerId } from "@/types/evespace";

export const STICKER_CATEGORIES: Array<{ id: StickerCategory; label: string }> = [
  { id: "favorites", label: "Favorites" },
  { id: "gifs", label: "GIFs" },
  { id: "people", label: "People" },
  { id: "characters", label: "Characters" },
  { id: "animals", label: "Animals" },
  { id: "food", label: "Food" },
  { id: "health", label: "Health" },
  { id: "games", label: "Games" },
  { id: "objects", label: "Objects" },
  { id: "nature", label: "Nature" },
  { id: "emotes", label: "Emotes" },
  { id: "spooky", label: "Spooky" },
  { id: "commerce", label: "Commerce" },
  { id: "media", label: "Media" },
  { id: "sports", label: "Sports" },
  { id: "beauty", label: "Beauty" },
  { id: "tech", label: "Tech" },
  { id: "fantasy", label: "Fantasy" },
  { id: "pixel", label: "Pixel" },
  { id: "doodle", label: "Doodle" },
  { id: "clay", label: "Clay" },
];

export const STICKERS: Sticker[] = [
  {
    id: "jake-gif",
    name: "Jake GIF",
    category: "gifs",
    src: "/stickers/ICONS8/GIF/jake.gif",
  },
  {
    id: "lol-face-gif",
    name: "LOL Face GIF",
    category: "gifs",
    src: "/stickers/ICONS8/GIF/lol-face.gif",
  },
  {
    id: "white-hello-kitty",
    name: "White Hello Kitty",
    category: "characters",
    src: "/stickers/ICONS8/characters/white-hello-kitty.png",
  },
  {
    id: "jake-face",
    name: "Jake Face",
    category: "characters",
    src: "/stickers/ICONS8/characters/jake-face.png",
  },
  {
    id: "coral-bird",
    name: "Coral Bird",
    category: "animals",
    src: "/stickers/ICONS8/animals/coral-bird.png",
  },
  {
    id: "singing-bird",
    name: "Singing Bird",
    category: "animals",
    src: "/stickers/ICONS8/animals/singing-bird.png",
  },
  {
    id: "blue-bird",
    name: "Blue Bird",
    category: "animals",
    src: "/stickers/ICONS8/animals/blue-bird.png",
  },
  {
    id: "pizza-slice",
    name: "Pizza Slice",
    category: "food",
    src: "/stickers/ICONS8/food/pizza-slice.png",
  },
  {
    id: "french-fries",
    name: "French Fries",
    category: "food",
    src: "/stickers/ICONS8/food/french-fries.png",
  },
  {
    id: "hamburger",
    name: "Hamburger",
    category: "food",
    src: "/stickers/ICONS8/food/hamburger.png",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    category: "food",
    src: "/stickers/ICONS8/food/strawberry.png",
  },
  {
    id: "sunny-side-up-egg",
    name: "Sunny Side Up Egg",
    category: "food",
    src: "/stickers/ICONS8/food/sunny-side-up-egg.png",
  },
  {
    id: "heart-pulse",
    name: "Heart Pulse",
    category: "health",
    src: "/stickers/ICONS8/health/heart-pulse.png",
  },
  {
    id: "brain",
    name: "Brain",
    category: "health",
    src: "/stickers/ICONS8/health/brain.png",
  },
  {
    id: "treatment-list",
    name: "Treatment List",
    category: "health",
    src: "/stickers/ICONS8/health/treatment-list.png",
  },
  {
    id: "gastrointestinal-tract",
    name: "Gastrointestinal Tract",
    category: "health",
    src: "/stickers/ICONS8/health/gastrointestinal-tract.png",
  },
  {
    id: "lungs",
    name: "Lungs",
    category: "health",
    src: "/stickers/ICONS8/health/lungs.png",
  },
  {
    id: "ambulance",
    name: "Ambulance",
    category: "health",
    src: "/stickers/ICONS8/health/ambulance.png",
  },
  {
    id: "knight-shield",
    name: "Knight Shield",
    category: "games",
    src: "/stickers/ICONS8/games/knight-shield.png",
  },
  {
    id: "spartan-helmet",
    name: "Spartan Helmet",
    category: "games",
    src: "/stickers/ICONS8/games/spartan-helmet.png",
  },
  {
    id: "knight-chess-piece",
    name: "Knight Chess Piece",
    category: "games",
    src: "/stickers/ICONS8/games/knight-chess-piece.png",
  },
  {
    id: "pacman",
    name: "Pacman",
    category: "games",
    src: "/stickers/ICONS8/games/pacman.png",
  },
  {
    id: "puzzle-pieces",
    name: "Puzzle Pieces",
    category: "games",
    src: "/stickers/ICONS8/games/puzzle-pieces.png",
  },
  {
    id: "magnet",
    name: "Magnet",
    category: "objects",
    src: "/stickers/ICONS8/objects/magnet.png",
  },
  {
    id: "bank-cards",
    name: "Bank Cards",
    category: "objects",
    src: "/stickers/ICONS8/objects/bank-cards.png",
  },
  {
    id: "office-desk",
    name: "Office Desk",
    category: "objects",
    src: "/stickers/ICONS8/objects/office-desk.png",
  },
  {
    id: "sun",
    name: "Sun",
    category: "nature",
    src: "/stickers/ICONS8/nature/sun.png",
  },
  {
    id: "star",
    name: "Star",
    category: "nature",
    src: "/stickers/ICONS8/nature/star.png",
  },
  {
    id: "night-cloud",
    name: "Night Cloud",
    category: "nature",
    src: "/stickers/ICONS8/nature/night-cloud.png",
  },
  {
    id: "sky-cloud",
    name: "Sky Cloud",
    category: "nature",
    src: "/stickers/ICONS8/nature/sky-cloud.png",
  },
  {
    id: "grinning-lol-face",
    name: "Grinning LOL Face",
    category: "emotes",
    src: "/stickers/ICONS8/emotes/grinning-lol-face.png",
  },
  {
    id: "red-heart",
    name: "Red Heart",
    category: "emotes",
    src: "/stickers/ICONS8/emotes/red-heart.png",
  },
  {
    id: "large-love-heart",
    name: "Large Love Heart",
    category: "emotes",
    src: "/stickers/ICONS8/emotes/large-love-heart.png",
  },
  {
    id: "two-hearts",
    name: "Two Hearts",
    category: "emotes",
    src: "/stickers/ICONS8/emotes/two-hearts.png",
  },
  {
    id: "pink-skull-heart",
    name: "Pink Skull Heart",
    category: "emotes",
    src: "/stickers/ICONS8/emotes/pink-skull-heart.png",
  },
  {
    id: "pink-heart",
    name: "Pink Heart",
    category: "emotes",
    src: "/stickers/ICONS8/emotes/pink-heart.png",
  },
  {
    id: "death-skull",
    name: "Death Skull",
    category: "spooky",
    src: "/stickers/ICONS8/spooky/death-skull.png",
  },
  {
    id: "small-death-skull",
    name: "Small Death Skull",
    category: "spooky",
    src: "/stickers/ICONS8/spooky/small-death-skull.png",
  },
  {
    id: "heart-skull",
    name: "Heart Skull",
    category: "spooky",
    src: "/stickers/ICONS8/spooky/heart-skull.png",
  },
  {
    id: "skeleton",
    name: "Skeleton",
    category: "spooky",
    src: "/stickers/ICONS8/spooky/skeleton.png",
  },
  {
    id: "warehouse",
    name: "Warehouse",
    category: "commerce",
    src: "/stickers/ICONS8/commerce/warehouse.png",
  },
  {
    id: "warehouse-building",
    name: "Warehouse Building",
    category: "commerce",
    src: "/stickers/ICONS8/commerce/warehouse-building.png",
  },
  {
    id: "factory",
    name: "Factory",
    category: "commerce",
    src: "/stickers/ICONS8/commerce/factory.png",
  },
  {
    id: "robotic-arm",
    name: "Robotic Arm",
    category: "commerce",
    src: "/stickers/ICONS8/commerce/robotic-arm.png",
  },
  {
    id: "free-shipping",
    name: "Free Shipping",
    category: "commerce",
    src: "/stickers/ICONS8/commerce/free-shipping.png",
  },
  {
    id: "support",
    name: "Support",
    category: "commerce",
    src: "/stickers/ICONS8/commerce/support.png",
  },
  {
    id: "truck",
    name: "Truck",
    category: "commerce",
    src: "/stickers/ICONS8/commerce/truck.png",
  },

  {
    id: "curling-stone",
    name: "Curling Stone",
    category: "sports",
    src: "/stickers/ICONS8/sports/curling-stone.png",
  },
  {
    id: "goal-target",
    name: "Goal Target",
    category: "sports",
    src: "/stickers/ICONS8/sports/goal-target.png",
  },
  {
    id: "soccer-player",
    name: "Soccer Player",
    category: "sports",
    src: "/stickers/ICONS8/sports/soccer-player.png",
  },
  {
    id: "flaming-basketball",
    name: "Flaming Basketball",
    category: "sports",
    src: "/stickers/ICONS8/sports/flaming-basketball.png",
  },
  {
    id: "football",
    name: "Football",
    category: "sports",
    src: "/stickers/ICONS8/sports/football.png",
  },
  {
    id: "penny-farthing",
    name: "Penny-Farthing",
    category: "sports",
    src: "/stickers/ICONS8/sports/penny-farthing.png",
  },
  {
    id: "first-place-medal",
    name: "First Place Medal",
    category: "sports",
    src: "/stickers/ICONS8/sports/first-place-medal.png",
  },
  {
    id: "weightlifting",
    name: "Weightlifting",
    category: "sports",
    src: "/stickers/ICONS8/sports/weightlifting.png",
  },
  {
    id: "punching-bag",
    name: "Punching Bag",
    category: "sports",
    src: "/stickers/ICONS8/sports/punching-bag.png",
  },
  {
    id: "walking-player",
    name: "Walking Player",
    category: "sports",
    src: "/stickers/ICONS8/sports/walking-player.png",
  },
  {
    id: "badminton-shuttlecock",
    name: "Badminton Shuttlecock",
    category: "sports",
    src: "/stickers/ICONS8/sports/badminton-shuttlecock.png",
  },
  {
    id: "trophy-bowl",
    name: "Trophy Bowl",
    category: "sports",
    src: "/stickers/ICONS8/sports/trophy-bowl.png",
  },
  {
    id: "silver-medal",
    name: "Silver Medal",
    category: "sports",
    src: "/stickers/ICONS8/sports/silver-medal.png",
  },
  {
    id: "rock-climber",
    name: "Rock Climber",
    category: "sports",
    src: "/stickers/ICONS8/sports/rock-climber.png",
  },
  {
    id: "gymnastics-bars",
    name: "Gymnastics Bars",
    category: "sports",
    src: "/stickers/ICONS8/sports/gymnastics-bars.png",
  },
  {
    id: "starting-pistol",
    name: "Starting Pistol",
    category: "sports",
    src: "/stickers/ICONS8/sports/starting-pistol.png",
  },
  {
    id: "golf-swing",
    name: "Golf Swing",
    category: "sports",
    src: "/stickers/ICONS8/sports/golf-swing.png",
  },
  {
    id: "tennis-racket",
    name: "Tennis Racket",
    category: "sports",
    src: "/stickers/ICONS8/sports/tennis-racket.png",
  },
  {
    id: "whistle",
    name: "Whistle",
    category: "sports",
    src: "/stickers/ICONS8/sports/whistle.png",
  },
  {
    id: "skis",
    name: "Skis",
    category: "sports",
    src: "/stickers/ICONS8/sports/skis.png",
  },
  {
    id: "golf-ball",
    name: "Golf Ball",
    category: "sports",
    src: "/stickers/ICONS8/sports/golf-ball.png",
  },
  {
    id: "hurdler",
    name: "Hurdler",
    category: "sports",
    src: "/stickers/ICONS8/sports/hurdler.png",
  },
  {
    id: "runner",
    name: "Runner",
    category: "sports",
    src: "/stickers/ICONS8/sports/runner.png",
  },
  {
    id: "dumbbell",
    name: "Dumbbell",
    category: "sports",
    src: "/stickers/ICONS8/sports/dumbbell.png",
  },
  {
    id: "soccer-ball",
    name: "Soccer Ball",
    category: "sports",
    src: "/stickers/ICONS8/sports/soccer-ball.png",
  },
  {
    id: "trophy-cup",
    name: "Trophy Cup",
    category: "sports",
    src: "/stickers/ICONS8/sports/trophy-cup.png",
  },
  {
    id: "sports-helmet",
    name: "Sports Helmet",
    category: "sports",
    src: "/stickers/ICONS8/sports/sports-helmet.png",
  },
  {
    id: "stopwatch",
    name: "Stopwatch",
    category: "sports",
    src: "/stickers/ICONS8/sports/stopwatch.png",
  },
  {
    id: "walking-person",
    name: "Walking Person",
    category: "sports",
    src: "/stickers/ICONS8/sports/walking-person.png",
  },
  {
    id: "running-person",
    name: "Running Person",
    category: "sports",
    src: "/stickers/ICONS8/sports/running-person.png",
  },
  {
    id: "barbell",
    name: "Barbell",
    category: "sports",
    src: "/stickers/ICONS8/sports/barbell.png",
  },
  {
    id: "second-place-medal",
    name: "Second Place Medal",
    category: "sports",
    src: "/stickers/ICONS8/sports/second-place-medal.png",
  },
  {
    id: "lipstick-and-brush",
    name: "Lipstick and Brush",
    category: "beauty",
    src: "/stickers/ICONS8/beauty/lipstick-and-brush.png",
  },
  {
    id: "facial-treatment",
    name: "Facial Treatment",
    category: "beauty",
    src: "/stickers/ICONS8/beauty/facial-treatment.png",
  },
  {
    id: "makeup-kit",
    name: "Makeup Kit",
    category: "beauty",
    src: "/stickers/ICONS8/beauty/makeup-kit.png",
  },
  {
    id: "processor",
    name: "Processor",
    category: "tech",
    src: "/stickers/ICONS8/tech/processor.png",
  },
  {
    id: "database",
    name: "Database",
    category: "tech",
    src: "/stickers/ICONS8/tech/database.png",
  },
  {
    id: "rocket",
    name: "Rocket",
    category: "tech",
    src: "/stickers/ICONS8/tech/rocket.png",
  },
  {
    id: "queen",
    name: "Queen",
    category: "fantasy",
    src: "/stickers/ICONS8/fantasy/queen.png",
  },
  {
    id: "unicorn",
    name: "Unicorn",
    category: "fantasy",
    src: "/stickers/ICONS8/fantasy/unicorn.png",
  },
  {
    id: "crystal-ball",
    name: "Crystal Ball",
    category: "fantasy",
    src: "/stickers/ICONS8/fantasy/crystal-ball.png",
  },
  {
    id: "royal-crown",
    name: "Royal Crown",
    category: "fantasy",
    src: "/stickers/ICONS8/fantasy/royal-crown.png",
  },
  {
    id: "orange-castle",
    name: "Orange Castle",
    category: "fantasy",
    src: "/stickers/ICONS8/fantasy/orange-castle.png",
  },
  {
    id: "sand-castle",
    name: "Sand Castle",
    category: "fantasy",
    src: "/stickers/ICONS8/fantasy/sand-castle.png",
  },
  {
    id: "purple-castle",
    name: "Purple Castle",
    category: "fantasy",
    src: "/stickers/ICONS8/fantasy/purple-castle.png",
  },
  {
    id: "mission-flag",
    name: "Mission Flag",
    category: "objects",
    src: "/stickers/ICONS8/objects/mission-flag.png",
  },
  {
    id: "language-bubble",
    name: "Language Bubble",
    category: "objects",
    src: "/stickers/ICONS8/objects/language-bubble.png",
  },
  {
    id: "towel",
    name: "Towel",
    category: "objects",
    src: "/stickers/ICONS8/objects/towel.png",
  },
  {
    id: "note-with-pen",
    name: "Note With Pen",
    category: "objects",
    src: "/stickers/ICONS8/objects/note-with-pen.png",
  },
  {
    id: "envelope",
    name: "Envelope",
    category: "objects",
    src: "/stickers/ICONS8/objects/envelope.png",
  },
  {
    id: "eraser",
    name: "Eraser",
    category: "objects",
    src: "/stickers/ICONS8/objects/eraser.png",
  },
  {
    id: "hand-towel",
    name: "Hand Towel",
    category: "objects",
    src: "/stickers/ICONS8/objects/hand-towel.png",
  },
  {
    id: "backpack",
    name: "Backpack",
    category: "objects",
    src: "/stickers/ICONS8/objects/backpack.png",
  },
  {
    id: "map-pin",
    name: "Map Pin",
    category: "objects",
    src: "/stickers/ICONS8/objects/map-pin.png",
  },
  {
    id: "hammer",
    name: "Hammer",
    category: "objects",
    src: "/stickers/ICONS8/objects/hammer.png",
  },
  {
    id: "chess-queen",
    name: "Chess Queen",
    category: "games",
    src: "/stickers/ICONS8/games/chess-queen.png",
  },
  {
    id: "toy-pistol",
    name: "Toy Pistol",
    category: "games",
    src: "/stickers/ICONS8/games/toy-pistol.png",
  },
  {
    id: "check-mark",
    name: "Check Mark",
    category: "emotes",
    src: "/stickers/ICONS8/emotes/check-mark.png",
  },
  {
    id: "farm",
    name: "Farm",
    category: "nature",
    src: "/stickers/ICONS8/nature/farm.png",
  },
  {
    id: "delivery-truck",
    name: "Delivery Truck",
    category: "commerce",
    src: "/stickers/ICONS8/commerce/delivery-truck.png",
  },
  {
    id: "yellow-factory",
    name: "Yellow Factory",
    category: "commerce",
    src: "/stickers/ICONS8/commerce/yellow-factory.png",
  },
  {
    id: "orange-cat",
    name: "Orange Cat",
    category: "favorites",
    src: "/stickers/ICONS8/orange-cat.png",
  },
  {
    id: "orange-corgi",
    name: "Orange Corgi",
    category: "favorites",
    src: "/stickers/ICONS8/orange-corgi.png",
  },
  {
    id: "purple-elephant",
    name: "Purple Elephant",
    category: "favorites",
    src: "/stickers/ICONS8/purple-elephant.png",
  },
  {
    id: "dog-bowl",
    name: "Dog Bowl",
    category: "favorites",
    src: "/stickers/ICONS8/dog-bowl.png",
  },
  {
    id: "lion-head",
    name: "Lion Head",
    category: "favorites",
    src: "/stickers/ICONS8/lion-head.png",
  },
  {
    id: "purple-cat",
    name: "Purple Cat",
    category: "favorites",
    src: "/stickers/ICONS8/purple-cat.png",
  },
  {
    id: "orange-tiger-head",
    name: "Orange Tiger Head",
    category: "favorites",
    src: "/stickers/ICONS8/orange-tiger-head.png",
  },
  {
    id: "pixel-butterfly",
    name: "Pixel Butterfly",
    category: "pixel",
    src: "/stickers/pixel-butterfly.png",
  },
  {
    id: "pixel-dolphin",
    name: "Pixel Dolphin",
    category: "pixel",
    src: "/stickers/pixel-dolphin.png",
  },
  {
    id: "pixel-egg",
    name: "Pixel Egg",
    category: "pixel",
    src: "/stickers/pixel-egg.png",
  },
  {
    id: "doodle-camera",
    name: "Doodle Camera",
    category: "doodle",
    src: "/stickers/doodle-camera.png",
  },
  {
    id: "doodle-chocolate",
    name: "Doodle Chocolate",
    category: "doodle",
    src: "/stickers/doodle-chocolate.png",
  },
  {
    id: "clay-carrot",
    name: "Clay Carrot",
    category: "clay",
    src: "/stickers/clay-carrot.png",
  },
  {
    id: "clay-duck",
    name: "Clay Duck",
    category: "clay",
    src: "/stickers/clay-duck.png",
  },
];

export function getSticker(stickerId: StickerId) {
  return STICKERS.find((sticker) => sticker.id === stickerId) ?? null;
}

const stickerIdSet = new Set(STICKERS.map((sticker) => sticker.id));

export function isRegisteredStickerId(id: string): id is StickerId {
  return stickerIdSet.has(id);
}
